name: Verify AWS Infra

on:
  push:
  pull_request:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  verify-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::730335381248:role/github-actions
          aws-region: ap-northeast-1

      - name: Install dependencies
        run: npm install

      - name: Verify CDK infrastructure
        run: npx cdk synth
