name: Verify AWS Infrastructure

on:
  push:
    paths:
      - 'infrastructure/**'
      - 'package.json'
  pull_request:
    paths:
      - 'infrastructure/**'
      - 'package.json'

jobs:
  verify-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          cd infrastructure && npm install

      - name: Build infrastructure code
        run: cd infrastructure && npm run build

      - name: Verify CDK infrastructure
        run: cd infrastructure && npx cdk synth
        env:
          CDK_DEFAULT_ACCOUNT: '123456789012'  # Dummy account for synth
          CDK_DEFAULT_REGION: 'us-east-1'      # Dummy region for synth
